"""init schema

Revision ID: c4c6751c149f
Revises: 
Create Date: 2025-08-27 01:35:53.215422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4c6751c149f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pokemon',
    sa.Column('nationalNo', sa.Integer(), nullable=False),
    sa.Column('paldeaNo', sa.Integer(), nullable=True),
    sa.Column('nameJa', sa.String(length=100), nullable=False),
    sa.Column('type1', sa.String(length=20), nullable=False),
    sa.Column('type2', sa.String(length=20), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('attack', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.Column('spAtk', sa.Integer(), nullable=False),
    sa.Column('spDef', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('nationalNo')
    )
    with op.batch_alter_table('Pokemon', schema=None) as batch_op:
        batch_op.create_index('ixPokemonNameJa', ['nameJa'], unique=False)
        batch_op.create_index(batch_op.f('ix_Pokemon_paldeaNo'), ['paldeaNo'], unique=False)

    op.create_table('User',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('passwordHash', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', name='uxUserName')
    )
    op.create_table('Regist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('nationalNo', sa.Integer(), nullable=False),
    sa.Column('dexType', sa.Enum('NATIONAL', 'PALDEA', name='dextype', native_enum=False), nullable=False),
    sa.CheckConstraint('"userId" > 0', name='ckRegistUserIdPositive'),
    sa.ForeignKeyConstraint(['nationalNo'], ['Pokemon.nationalNo'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId', 'nationalNo', 'dexType', name='uxRegistUnique')
    )
    with op.batch_alter_table('Regist', schema=None) as batch_op:
        batch_op.create_index('ixRegistNational', ['nationalNo'], unique=False)
        batch_op.create_index('ixRegistUserDex', ['userId', 'dexType'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Regist', schema=None) as batch_op:
        batch_op.drop_index('ixRegistUserDex')
        batch_op.drop_index('ixRegistNational')

    op.drop_table('Regist')
    op.drop_table('User')
    with op.batch_alter_table('Pokemon', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Pokemon_paldeaNo'))
        batch_op.drop_index('ixPokemonNameJa')

    op.drop_table('Pokemon')
    # ### end Alembic commands ###
