# PowerShell用: おたよりナビ マイグレーション状態確認（SSM経由）

Write-Host "=========================================="
Write-Host "おたよりナビ マイグレーション状態確認（SSM経由）"
Write-Host "=========================================="
Write-Host ""

# おたよりナビ用EC2インスタンスID（確認スクリプトの結果から）
$INSTANCE_ID = "i-001cd3b0db58d9f78"
$REGION = "ap-northeast-1"

Write-Host "=== AWS Systems Manager Session Managerで接続 ==="
Write-Host ""
Write-Host "以下のコマンドを実行してください:"
Write-Host ""
Write-Host "aws ssm start-session --target $INSTANCE_ID --region $REGION"
Write-Host ""
Write-Host "接続後、以下のコマンドを実行:"
Write-Host ""
Write-Host "cd /home/ec2-user/otayori-navi"
Write-Host "docker compose --env-file .env exec -T app sh -c '"
Write-Host "  export SHARED_DATABASE_URL=`$OTAYORI_NAVI_DATABASE_URL"
Write-Host "  export PYTHONPATH=/app/src:/app/../dev-workspace:/app/../FishTrack/src:/app/../MyPokedex/src:/app/../otayori-navi/src"
Write-Host "  cd /app/../dev-workspace"
Write-Host "  python3 scripts/check_otayori_navi_migration.py"
Write-Host "'"
Write-Host ""
Write-Host "または、直接SQLで確認する場合:"
Write-Host ""
Write-Host "docker compose --env-file .env exec -T app sh -c '"
Write-Host "  export PGPASSWORD=`$(echo `$OTAYORI_NAVI_DATABASE_URL | sed -n \"s/.*:\\([^@]*\\)@.*/\\1/p\")"
Write-Host "  psql -h shared-db.cty4osc6gw6k.ap-northeast-1.rds.amazonaws.com -U shared_user -d shared_db -c \""
Write-Host "    SELECT version_num FROM alembic_version ORDER BY version_num; "
Write-Host "  \""
Write-Host "  psql -h shared-db.cty4osc6gw6k.ap-northeast-1.rds.amazonaws.com -U shared_user -d shared_db -c '"
Write-Host "    SELECT table_name FROM information_schema.tables WHERE table_schema = ''public'' AND table_name IN (''families'', ''users'', ''family_invites'', ''documents'');"
Write-Host "  '"
Write-Host "'"
Write-Host ""
Write-Host "=========================================="
