# PowerShell逕ｨ: 縺翫◆繧医ｊ繝翫ン config.yaml遒ｺ隱搾ｼ・SM邨檎罰・・
Write-Host "=========================================="
Write-Host "縺翫◆繧医ｊ繝翫ン config.yaml遒ｺ隱搾ｼ・SM邨檎罰・・
Write-Host "=========================================="
Write-Host ""

$INSTANCE_ID = "i-001cd3b0db58d9f78"
$REGION = "ap-northeast-1"

Write-Host "=== AWS Systems Manager Session Manager縺ｧ謗･邯・==="
Write-Host ""
Write-Host "莉･荳九・繧ｳ繝槭Φ繝峨ｒ螳溯｡後＠縺ｦ縺上□縺輔＞:"
Write-Host ""
Write-Host "aws ssm start-session --target $INSTANCE_ID --region $REGION"
Write-Host ""
Write-Host "謗･邯壼ｾ後∽ｻ･荳九・繧ｳ繝槭Φ繝峨ｒ螳溯｡・"
Write-Host ""
Write-Host "cd /home/ec2-user/otayori-navi"
Write-Host "docker compose --env-file .env exec -T app sh -c '"
Write-Host "  export PYTHONPATH=/app/src:/app/../dev-workspace:/app/../FishTrack/src:/app/../MyPokedex/src:/app/../otayori-navi/src"
Write-Host "  cd /app/../dev-workspace"
Write-Host "  python3 scripts/check_otayori_navi_config.py"
Write-Host "'"
Write-Host ""
Write-Host "縺ｾ縺溘・縲∫峩謗･config.yaml縺ｮ蜀・ｮｹ繧堤｢ｺ隱阪☆繧句ｴ蜷・"
Write-Host ""
Write-Host "cd /home/ec2-user/otayori-navi"
Write-Host "cat config.yaml"
Write-Host ""
Write-Host "=========================================="